image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: feature/

containerPort: 8080
secretEnabled: false

vars:
  SPRING_PROFILES_ACTIVE: devt
  K8SCC_ENV: DEVT

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

