image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 30d122cab5b2c476323d8fc19d02d8988b8b41f0

containerPort: 8080

vars:
  SPRING_PROFILES_ACTIVE: devt
  K8SCC_ENV: DEVT

ingress:
  host: devt-k8scc.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

