image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 4a34f02332fa5734f883dce0bb80141062f3cad4

container:
  imagePullPolicy: Always

containerPort: 8080

vars:
  SPRING_PROFILES_ACTIVE: devt
  K8SCC_ENV: DEVT

ingress:
  host: devt-k8scc.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

