image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: dee64eb96802e70f38226871cb4c622fe174c584

containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: ACPT