image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: a4f9b807561c11d28b7676eed46f9099f38c18dd

containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: ACPT