image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: c7dca46dcc39cdffa0bf5351dfec0eecd23d370d

containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: ACPT