image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 418cc8fdd9ba59c6ecb292770d70e15fc0937888

containerPort: 8080
secretEnabled: false

ingress:
  host: k8scc.internal

vars:
  SPRING_PROFILES_ACTIVE: test
  K8SCC_ENV: TEST

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

