image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: dee64eb96802e70f38226871cb4c622fe174c584

containerPort: 8080
secretEnabled: true

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  host: webclient

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: DEVT



resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"
