image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 886e1513ac6b8ab83c0cae9e30f5b4cafc9e9fe1

containerPort: 8080
secretEnabled: false

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  host: webclient

vars:
  SPRING_PROFILES_ACTIVE: devt
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: DEVT

fileSecrets:
  - name: devt-properties
    path: /config
    secrets:
      application-devt.yaml: |
        debug: true
        spring:
          main:
            banner-mode: off

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"
