image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: b142529b0262cd1a663c475c205d61fc314c4ad4

containerPort: 8080
secretEnabled: true

vars:
  SPRING_PROFILES_ACTIVE: devt
  SPRING_CONFIG_IMPORT: configserver:http://${CFG_USER}:${CFG_PASS}@k8scc-config-server:8080
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: DEVT

