image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 72d52f7a5307866985dcc9b8fbd5a4f7fe401edc

containerPort: 8080


ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  host: prwebclient

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: DEVT



resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"
