image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: d57c5fe40d86fa7121dd5001afc662c597df4977

containerPort: 8080
secretEnabled: false

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  host: webclient

vars:
  SPRING_PROFILES_ACTIVE: devt
  K8SCC_ENV: DEVT

fileSecrets:
  - name: devt-properties
    path: /config2
    secrets:
      application-devt.yaml: |
        debug: false
        spring:
          main:
            banner-mode: off

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

volumes:
  - name: props
    path: /config
    fileName: application-devt.yaml
    fileContent: |
      debug: false
      spring:
        main:
          banner-mode: on

