image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: b142529b0262cd1a663c475c205d61fc314c4ad4

containerPort: 8080

vars:
  SPRING_PROFILES_ACTIVE: devt
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: DEVT


#  spring.cloud.config.server.git.uri=https://github.com/rmortale/spring-config-repo
#  spring.cloud.config.server.git.clone-on-start=true
#  spring.security.user.name=root
#  spring.security.user.password=secret
#  logging.level.org.springframework.cloud.config.server=TRACE