image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 64a07aa01a14dcf4a765ab529bf556f269da19f4

containerPort: 8080
secretEnabled: true

vars:
  SPRING_PROFILES_ACTIVE: devt
  SPRING_CONFIG_IMPORT: configserver:http://${CFG_USER}:${CFG_PASS}@k8scc-config-server:8080
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: DEVT

