image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: f0e88e9434bdd111f86e0773fc28455814fd8ee1

containerPort: 8080
secretEnabled: false

vars:
  SPRING_PROFILES_ACTIVE: prod
  K8SCC_ENV: PROD

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

