image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: a2e576c

containerPort: 8080

vars:
  K8SCC_ENV: DEVT

ingress:
  host: devt-k8scc.internal


resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

