image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: e570dd50efec0451e071498d706182321431abeb

containerPort: 8080
secretEnabled: false

vars:
  SPRING_PROFILES_ACTIVE: test
  K8SCC_ENV: DEVT

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

