image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: c67db0ae3ec5aa364b9c42b6e79ae0a91d1575c5

containerPort: 8080
secretEnabled: false

vars:
  SPRING_PROFILES_ACTIVE: test
  K8SCC_ENV: TEST

resources:
  limits:
    cpu: "500m"
    memory: "1000Mi"
  requests:
    cpu: "200m"
    memory: "500Mi"

      

