image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 64a07aa01a14dcf4a765ab529bf556f269da19f4

containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: PROD
