image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: d57c5fe40d86fa7121dd5001afc662c597df4977

replicas: 3
containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: ACPT
  SPRING_PROFILES_ACTIVE: acpt

fileSecrets:
  - name: acpt-properties
    path: /config
    secrets:
      application-acpt.yaml: |
        debug: false
        spring:
          main:
            banner-mode: on
