image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 886e1513ac6b8ab83c0cae9e30f5b4cafc9e9fe1

replicas: 3
containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: PROD
