image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: d57c5fe40d86fa7121dd5001afc662c597df4977

replicas: 3
containerPort: 8080
secretEnabled: true

vars:
  K8SCC_ENV: ACPT
  SPRING_PROFILES_ACTIVE: acpt

volumes:
  - name: props
    path: /config
    fileName: application-acpt.yaml
    fileContent: |
      debug: false