image:
  repository: ghcr.io/rmortale/k8scc-web-client
  tag: 5088c0066e076ea1358500d17674de370d214e47

containerPort: 8080
secretEnabled: true

vars:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
  K8SCC_ENV: PROD
