apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8scc-web-client-devt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: k8scc-web-client-app
spec:
  project: default
  destination:
    name: in-cluster
    namespace: k8scc
  sources:
    - chart: onechart
      repoURL: https://chart.onechart.dev
      targetRevision: 0.73.0
      helm:
        valueFiles:
          - $values/k8s/helm-values/devt-values.yaml

    - repoURL: https://github.com/rmortale/k8scc-web-client.git
      ref: values
      targetRevision: devt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
